name = "cdn-worker"
type = "javascript"
zone_id = "31ef5324904df8e826d642e739af38f8"
account_id = "78e1d5140b47fc9dab18dc8b25351b7a"
compatibility_date = "2022-01-19"
route = "ampjs.org/*"
kv_namespaces = [
  { binding = "RTV", id = "f33b97f2e1434004975c0d8553f70488", preview_id = "192df3dff1b345ce8e7c794329bb7ccd" },
  { binding = "CONFIG", id = "b03e5db05f3e4d068508da267e248949", preview_id = "69318ded67c0477b85d73ec801b47543" }
]

[wasm_modules]
BROTLI_WASM = 'node_modules/brotli-wasm/pkg.bundler/brotli_wasm_bg.wasm'

[build]
command = "npm ci && npm run build"
[build.upload]
format = "service-worker"
