main = "./dist/worker.mjs"
compatibility_date = "2022-12-08"
account_id = "78e1d5140b47fc9dab18dc8b25351b7a"
usage_model = "unbound"
no_bundle = true

[env.production]
name = "cdn-worker"
route = "ampjs.org/*"
kv_namespaces = [
  { binding = "RTV", id = "f33b97f2e1434004975c0d8553f70488", preview_id = "192df3dff1b345ce8e7c794329bb7ccd" },
  { binding = "CONFIG", id = "b03e5db05f3e4d068508da267e248949", preview_id = "69318ded67c0477b85d73ec801b47543" }
]

[env.production.vars]
STORAGE_BASE_URL = "https://pub-857751ce270b4ed4b8b5a2baa3212e8d.r2.dev/org-cdn/rtv/"

[env.staging]
name = "cdn-worker-staging"
workers_dev = true
kv_namespaces = [
  { binding = "RTV", id = "f33b97f2e1434004975c0d8553f70488", preview_id = "192df3dff1b345ce8e7c794329bb7ccd" },
  { binding = "CONFIG", id = "b03e5db05f3e4d068508da267e248949", preview_id = "69318ded67c0477b85d73ec801b47543" }
]

[env.staging.vars]
STORAGE_BASE_URL = "https://pub-857751ce270b4ed4b8b5a2baa3212e8d.r2.dev/org-cdn/rtv/"

[env.development]
name = "cdn-worker-development"
workers_dev = true
kv_namespaces = [
  { binding = "RTV", id = "192df3dff1b345ce8e7c794329bb7ccd", preview_id = "192df3dff1b345ce8e7c794329bb7ccd" },
  { binding = "CONFIG", id = "69318ded67c0477b85d73ec801b47543", preview_id = "69318ded67c0477b85d73ec801b47543" }
]

[env.development.vars]
STORAGE_BASE_URL = "https://pub-857751ce270b4ed4b8b5a2baa3212e8d.r2.dev/org-cdn/rtv/"

[wasm_modules]
BROTLI_WASM = "node_modules/brotli-wasm/pkg.bundler/brotli_wasm_bg.wasm"

[build]
command = "npm ci && npm run build"
watch_dir = "src"
