name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    if: github.repository == 'ampproject/cdn-worker'
    environment: wrangler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
